
server:
  port: 9090
  servlet:
    context-path: /author
# 可以debugger 模式运行
debug: false
# spring 相关配置
spring:
  profiles:
    active: dev

  thymeleaf:
      cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
      proxy-target-class: true
mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.zbcn.authormanager.author.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
      jdbc-type-for-null: null
  global-config:
    banner: false
