DROP TABLE IF EXISTS t_auth_user;/*SkipError*/
CREATE TABLE t_auth_user(
    USER_ID BIGINT NOT NULL AUTO_INCREMENT  COMMENT '用户ID 主键' ,
    USERNAME VARCHAR(128) NOT NULL   COMMENT '用户名' ,
    PASSWORD VARCHAR(128) NOT NULL   COMMENT '密码' ,
    DEPT_ID BIGINT    COMMENT '部门ID 部门Id' ,
    EMAIL VARCHAR(128)    COMMENT '邮箱' ,
    MOBILE VARCHAR(32)    COMMENT '联系电话' ,
    STATUS VARCHAR(32) NOT NULL   COMMENT '状态 0锁定 1有效' ,
    GENDER VARCHAR(1)    COMMENT '性别 0男 1女 2保密' ,
    IS_TAB VARCHAR(1)    COMMENT '是否开启tab 0关闭 1开启' ,
    THEME VARCHAR(128)    COMMENT '主题' ,
    AVATAR VARCHAR(32)    COMMENT '头像' ,
    DESCRIPTION VARCHAR(512)    COMMENT '描述' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    LAST_LOGIN_TIME DATETIME    COMMENT '最近访问时间' ,
    PRIMARY KEY (USER_ID)
) COMMENT = '用户名 用户名';

ALTER TABLE t_auth_user ADD UNIQUE USER_ID_INDEX(USER_ID);
ALTER TABLE t_auth_user COMMENT '用户名';


DROP TABLE IF EXISTS t_auth_dept;/*SkipError*/
CREATE TABLE t_auth_dept(
    DEPT_ID BIGINT NOT NULL AUTO_INCREMENT  COMMENT '部门ID' ,
    PARENT_ID BIGINT NOT NULL   COMMENT '上级部门ID' ,
    DEPT_NAME VARCHAR(128) NOT NULL   COMMENT '部门名称' ,
    ORDER_NUM VARCHAR(32)    COMMENT '显示排序' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (DEPT_ID)
) COMMENT = '部门表 部门表';

ALTER TABLE t_auth_dept ADD UNIQUE DEPT_ID_INDEX(DEPT_ID);
ALTER TABLE t_auth_dept COMMENT '部门表';
DROP TABLE IF EXISTS t_auth_role;/*SkipError*/
CREATE TABLE t_auth_role(
    ROLE_ID BIGINT NOT NULL AUTO_INCREMENT  COMMENT '角色ID' ,
    ROLE_NAME VARCHAR(128) NOT NULL   COMMENT '角色名称' ,
    REMARK VARCHAR(32)    COMMENT '角色描述' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (ROLE_ID)
) COMMENT = '角色表 角色表';

ALTER TABLE t_auth_role COMMENT '角色表';

DROP TABLE IF EXISTS t_auth_menu;/*SkipError*/
CREATE TABLE t_auth_menu(
    MENU_ID BIGINT NOT NULL AUTO_INCREMENT  COMMENT '菜单/按钮ID' ,
    PARENT_ID BIGINT NOT NULL   COMMENT '上级菜单ID' ,
    MENU_NAME VARCHAR(128)    COMMENT '菜单/按钮名称' ,
    URL VARCHAR(128)    COMMENT '菜单URL' ,
    PERMS TEXT    COMMENT '权限标识' ,
    ICON VARCHAR(64)    COMMENT '图标' ,
    TYPE VARCHAR(1) NOT NULL   COMMENT '类型 0菜单 1按钮' ,
    ORDER_NUM BIGINT    COMMENT '排序' ,
    CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    PRIMARY KEY (MENU_ID)
) COMMENT = '菜单表 菜单表';

ALTER TABLE t_auth_menu ADD UNIQUE MENU_ID_INDEX(MENU_ID);
ALTER TABLE t_auth_menu COMMENT '菜单表';

DROP TABLE IF EXISTS t_role_menu;/*SkipError*/
CREATE TABLE t_role_menu(
    ROLE_ID BIGINT NOT NULL   COMMENT '角色ID' ,
    MENU_ID BIGINT NOT NULL   COMMENT '菜单/按钮ID' 
) COMMENT = '角色_资源表 角色菜单关联表';

ALTER TABLE t_role_menu COMMENT '角色_资源表';


DROP TABLE IF EXISTS t_user_role;/*SkipError*/
CREATE TABLEt_user_role(
    USER_ID BIGINT NOT NULL   COMMENT '用户ID' ,
    ROLE_ID BIGINT NOT NULL   COMMENT '角色ID' 
) COMMENT = '用户角色关系表 用户角色关联关系';

ALTER TABLE t_user_role COMMENT '用户角色关系表';


DROP TABLE IF EXISTS t_login_log;/*SkipError*/
CREATE TABLE t_login_log(
    ID BIGINT NOT NULL AUTO_INCREMENT  COMMENT 'ID主键' ,
    USERNAME VARCHAR(128) NOT NULL   COMMENT '登录人' ,
    LOGIN_TIME DATETIME NOT NULL   COMMENT '登录时间' ,
    LOCATION VARCHAR(512) NOT NULL   COMMENT '登录地点' ,
    IP VARCHAR(128) NOT NULL   COMMENT 'IP地址' ,
    OPER_SYSTEM VARCHAR(32) NOT NULL   COMMENT '操作系统' ,
    BROWSER VARCHAR(128) NOT NULL   COMMENT '浏览器' ,
    PRIMARY KEY (ID)
) COMMENT = '登录日志 登录日志';

ALTER TABLE t_login_log ADD UNIQUE ID_INDEX(ID);
ALTER TABLE t_login_log COMMENT '登录日志';
